language: php
dist: bionic
os: linux

php:
  - 7.1
  - 7.2
  - 7.3

jobs:
  include:
    - php: 5.6
      env: EWAY_API_VERSION=31
      dist: xenial
    - php: 5.6
      env: EWAY_API_VERSION=40
      dist: xenial
  fast_finish: true

env:
 - EWAY_API_VERSION=31
 - EWAY_API_VERSION=40

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - COMPOSER_MEMORY_LIMIT=-1 travis_retry composer install --prefer-dist --no-interaction --optimize-autoloader

script:
  - composer phpcs
  - composer test