language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

matrix:
    fast_finish: true
    include:
     - php: hhvm
       script: phpunit --testsuite integration

cache:
    directories:
        - $HOME/.composer/cache

sudo: false

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist --no-interaction --optimize-autoloader
