language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7

sudo: false

env:
  - COMPOSER_OPTS=""
  - COMPOSER_OPTS="--prefer-lowest"

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer update $COMPOSER_OPTS
