language: php
dist: xenial
os: linux

php:
  - 5.6
  - 7.1
  - 7.2

jobs:
  fast_finish: true

env:
 - EWAY_API_VERSION=31
 - EWAY_API_VERSION=40

cache:
    directories:
        - $HOME/.composer/cache

before_install:
  - composer self-update
  - composer validate

install:
  - travis_retry composer install --prefer-dist --no-interaction --optimize-autoloader
